### ISSUE TITLE
Is it possible to create datastore automatically?

### ISSUE THREAD

**Issue by supakornkim** [gluons/vue-thailand-address#42]
Dear Mr,

Vue-thailand-address is very awesome. 
But I have a case that I need to use it in a multiple set of input. (Click Add more..for example)

I would like to know how to make datastore auto created in each time we click add more button.

Appreciate your advise.
Thanks.

**Comment by gluons** [comment]
You can use [List Rendering](https://vuejs.org/v2/guide/list.html) to render you list of address components.

I've created [demo page](https://vue-thailand-address.netlify.com/demo) for this.  
You can also see the source code [here](https://github.com/gluons/vue-thailand-address/blob/docs/src/views/Demo.vue).
