### ISSUE TITLE
Default export of the module has or is using private name 'VueConstructor'

### ISSUE THREAD

**Issue by gluons** [gluons/vue-thailand-address#5]
ไม่สามารถ build ผ่านได้เมื่อ upgrade เป็น **Vue 2.5**  
พบกับ error

```
Default export of the module has or is using private name 'VueConstructor'
```

เป็นปัญหาที่เกิดจาก `compilerOptions` -> `declaration: true` ใน `tsconfig.json`

**ใน forum:** https://forum.vuejs.org/t/default-export-of-the-module-has-or-is-using-private-name-vueconstructor/19624

**Repo ที่ใช้ repro ปัญหานี้:** [gluons/vue-typescript-export-issue](https://github.com/gluons/vue-typescript-export-issue)

รายงานปัญหาแล้วที่ vuejs/vue#6999

**Comment by gluons** [comment]
Temporarily fix by 6ad06294c47459c30444fd2c0f34f6672f4a9f0a

**Comment by gluons** [comment]
**Update:** Waiting for vuejs/vue#7002 to be released. 🙌

**Comment by gluons** [comment]
[Vue v2.5.4 released.](https://github.com/vuejs/vue/releases/tag/v2.5.4) 🎉

I'm going to upgrade.

**Comment by trusktr** [comment]
I've opened a request to fix this in TypeScript. https://github.com/microsoft/TypeScript/issues/35822
