### ISSUE TITLE
สามารถเปลี่ยน type input ของ zip code ได้มั้ยคะ

### ISSUE THREAD

**Issue by fahstjlps** [gluons/vue-thailand-address#51]
พอดีอยากจะให้ zip code เป็น
<input type="number" /> หรือไม่ก็ <input type="tel" /> ค่ะ เวลาใช้ mobile จะได้เปิดเป็น number pad น่ะค่ะ

ตอนนี้ใส่  attribute type="number" ตรง component เลยค่ะ แต่ทำไม่ได้
พอจะมีิวิธีไหนทำได้บ้างมั้ยคะ รบกวนด้วยค่ะ

**Comment by gluons** [comment]
เพิ่ม prop ชื่อ `numbered` สำหรับ [zipcode](https://vue-thailand-address.netlify.com/api/zipcode) ใน v3.3.0 ให้แล้วนะครับ

**Comment by fahstjlps** [comment]
ขอบคุณมากค่า


ในวันที่ อา. 8 มี.ค. 2020 21:00 Saran Tanpituckpong ✅ <
notifications@github.com> เขียนว่า:
